### PR TITLE
add: google vertex ai embedding function

### PR DESCRIPTION
**Pull request by iwilltry42**
Official documentation: https://cloud.google.com/vertex-ai/generative-ai/docs/embeddings/get-text-embeddings#generative-ai-get-text-embedding-drest

### CODE REVIEW

**Review by philippgille — COMMENTED** [review]
That's perfect, I already wanted to add Vertex, Bedrock and Voyage AI! :+1: 

WDYT about using Vertex or GCP in the var/struct/function names instead of Google? Then Amazon would be Bedrock or AWS.

And regarding the options, WDYT about using the builder pattern (e.g. last section in https://rednafi.com/go/dysfunctional_options_pattern/)?

**Comment by iwilltry42** [comment]
@philippgille I renamed the provider to vertex and switched to using the builder pattern as you suggested - I have no strong preference there.
One nit I have is that now the signature looks quite different from the other providers, so we may want to adjust them as well at some point in a breaking change. WDYT?

**Comment by philippgille** [comment]
> @philippgille I renamed the provider to vertex and switched to using the builder pattern as you suggested - I have no strong preference there.
> One nit I have is that now the signature looks quite different from the other providers, so we may want to adjust them as well at some point in a breaking change. WDYT?

Oh you changed it already :zap: , sorry I just wanted to hear your thoughts first.

One way to not change the existing embedding func constructor signatures is to only use the builder pattern for the optional options struct that you created initially. So keeping the mandatory config (like API key) as individual params in the `NewEmbeddingFunc...()` signature, and adding a config struct for the optional configs as last param. That config struct then has the `With...()` methods.

That gives us:
- The existing constructors that only have mandatory options can stay the same
- Fewer global package members (no `chromem.With...()` function for each optional option)
- Subjectively simpler due to passing a struct instead of variadic functions
- No risk of naming conflicts with options for other embedding providers. (For example `grpc-go` has one `WithChainUnaryInterceptor()` to create a `ClientOption` and `ChainUnaryInterceptor()` (without the `With` prefix) to create a `ServerOption`, making it inconsistent)

And the parameter for the optional config can be a pointer, so people can pass nil, in which case we use the default options. So people don't have to call call *two* constructor functions.

The one downside of that approach is that for this latter case (default config for the optional options) you still have to explicitly pass nil, instead of omitting the param like the variadic functions allow.

---

To not put the burden on you, I'll merge this PR and create another PR with my suggestion.

Thanks again!

**Comment by philippgille** [comment]
- PR with suggestion: https://github.com/philippgille/chromem-go/pull/92
- PR to alternatively go back to variadic functions: https://github.com/philippgille/chromem-go/pull/93

**Pull request merged**
